build:
  number: 4
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

package:
  name: gap2seq
  version: "2.0"
source:
  fn: Gap2Seq-2.0.tar.gz
  url: https://www.cs.helsinki.fi/u/lmsalmel/Gap2Seq/Gap2Seq-2.0.tar.gz
  md5: 67af9e2ac4171dbbeff569115705405c
  patches: # [osx]
    - 0001-use-boost-unordered-map-and-set-in-lieu-of-standard.patch # [osx]
requirements:
  build:
    # linux build
    - gcc >=4.7 # [linux]
    - boost {{CONDA_BOOST}}* # [linux]
    # osx build
    - llvm # [osx]
    - llvmdev ==3.9.1 # [osx]
    - libcxx # [osx]
    - boost ==1.63.0 # [osx]
    # general requirements
    - libgcc
    - zlib
    - cmake
    - make
  run:
    - zlib
    - libgcc # [linux]
    - libcxx # [osx]
    - boost {{CONDA_BOOST}}* # [linux]
    - boost ==1.63.0 # [osx]
test:
  commands:
     - GapMerger 2>&1 | grep "USAGE for"  > /dev/null
     - GapCutter 2>&1 | grep "USAGE for"  > /dev/null
     - Gap2Seq 2>&1 | grep "USAGE for"  > /dev/null
     - Gap2Seq.sh 2>&1 | grep "Required parameters" > /dev/null

about:
  home: https://www.cs.helsinki.fi/u/lmsalmel/Gap2Seq/
  license: GPLv3
  license_file: LICENCE
  summary: Gap2Seq is a tool for filling gaps between contigs in genome assemblies.
