build:
  number: 0
  skip: True # [osx]

package:
  name: ped_parser
  version: "1.6.5"

source:
  fn: ped_parser-1.6.5.tar.gz
  url: https://pypi.python.org/packages/source/p/ped_parser/ped_parser-1.6.5.tar.gz
  md5: 1f404e131c3d210d32e6253ac500b200

requirements:
  build:
    - python
    - setuptools
    - pytest
    - click

  run:
    - python
    - pytest
    - click

test:
  imports:
    - ped_parser
  commands:
    # click requires a unicode locale
    - LANG=C.UTF-8 ped_parser --help

about:
  home: https://github.com/moonso/ped_parser
  license: BSD License
  summary: 'A ped file parser.'

extra:
  container:
    # click relies on unicode support, which is not present in the default busybox image
    base: debian:latest
