package:
  name: qiime
  version: "1.9.1"

source:
  fn: qiime-1.9.1.tar.gz
  url: https://pypi.python.org/packages/source/q/qiime/qiime-1.9.1.tar.gz
  md5: 32d4db2b2c888dbbfc6aa33f02725526
  sha1: 2ab4ac9beb745ed3eca3243312cc9ce14e8a20d8
  sha256: c12dcdae1fe44762a49668276d7e93f487d87a0dc2ff8ca696ac0eff9d92a8a8

build:
  number: 1
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.14.0
    - cogent ==1.5.3
    - natsort <4.0.0
    - pynast ==1.2.2
    - qcli >=0.1.1,<0.2.0
    - gdata
    - biom-format >=2.1.4,<2.2.0
    - emperor >=0.9.51,<1.0.0
    - scikit-bio >=0.2.3,<0.3.0
    - matplotlib <=1.9
    - burrito-fillings >=0.1.1,<0.2.0
    - pandas >=0.13.1
    - burrito >=0.9.1,<1.0.0
    - qiime-default-reference >=0.1.2,<0.2.0
    - mock
    - nose
    - xz

  run:
    - python
    - numpy x.x
    - scipy >=0.14.0
    - cogent ==1.5.3
    - natsort <4.0.0
    - pynast ==1.2.2
    - qcli >=0.1.1,<0.2.0
    - gdata
    - biom-format >=2.1.4,<2.2.0
    - emperor >=0.9.51,<1.0.0
    - scikit-bio >=0.2.3,<0.3.0
    - matplotlib <=1.9
    - burrito-fillings >=0.1.1,<0.2.0
    - pandas >=0.13.1
    - burrito >=0.9.1,<1.0.0
    - qiime-default-reference >=0.1.2,<0.2.0
    - mock
    - nose
    - libgcc
    - glib
    - xorg-libxext
    - xorg-libxdmcp
    - xorg-libsm
    - xorg-libxrender
    - xorg-libxau
    - xz

test:
  # Python imports
  imports:
    - qiime
    - qiime.util
    - qiime.check_id_map
    - qiime.sort

  commands:
    - LANG=C.UTF-8 add_alpha_to_mapping_file.py -h
    - LANG=C.UTF-8 add_qiime_labels.py -h
    - LANG=C.UTF-8 adjust_seq_orientation.py -h
    - LANG=C.UTF-8 align_seqs.py -h
    - LANG=C.UTF-8 alpha_diversity.py -h
    - LANG=C.UTF-8 alpha_rarefaction.py -h
    - LANG=C.UTF-8 amplicon_contingency_table.py # no option
    - LANG=C.UTF-8 ampliconnoise.py -h
    - LANG=C.UTF-8 assign_taxonomy.py -h
    - LANG=C.UTF-8 beta_diversity.py -h
    - LANG=C.UTF-8 beta_diversity_through_plots.py -h
    - LANG=C.UTF-8 beta_significance.py -h
    - LANG=C.UTF-8 blast_wrapper.py -h
    - LANG=C.UTF-8 categorized_dist_scatterplot.py -h
    - LANG=C.UTF-8 check_id_map.py -h
    - LANG=C.UTF-8 clean_raxml_parsimony_tree.py -h
    - LANG=C.UTF-8 cluster_quality.py -h
    - LANG=C.UTF-8 collapse_samples.py -h
    - LANG=C.UTF-8 collate_alpha.py -h
    - LANG=C.UTF-8 compare_alpha_diversity.py -h
    - LANG=C.UTF-8 compare_categories.py -h
    - LANG=C.UTF-8 compare_distance_matrices.py -h
    - LANG=C.UTF-8 compare_taxa_summaries.py -h
    - LANG=C.UTF-8 compare_trajectories.py -h
    - LANG=C.UTF-8 compute_core_microbiome.py -h
    - LANG=C.UTF-8 compute_taxonomy_ratios.py -h
    - LANG=C.UTF-8 conditional_uncovered_probability.py -h
    - LANG=C.UTF-8 consensus_tree.py -h
    - LANG=C.UTF-8 convert_fastaqual_fastq.py -h
    - LANG=C.UTF-8 convert_unifrac_sample_mapping_to_otu_table.py -h
    - LANG=C.UTF-8 core_diversity_analyses.py -h
    - LANG=C.UTF-8 count_seqs.py -h
    - LANG=C.UTF-8 demultiplex_fasta.py -h
    - LANG=C.UTF-8 denoise_wrapper.py -h
    - LANG=C.UTF-8 denoiser.py -h
    - LANG=C.UTF-8 denoiser_preprocess.py -h
    - LANG=C.UTF-8 denoiser_worker.py -h
    - LANG=C.UTF-8 detrend.py -h
    - LANG=C.UTF-8 differential_abundance.py -h
    - LANG=C.UTF-8 dissimilarity_mtx_stats.py -h
    - LANG=C.UTF-8 distance_matrix_from_mapping.py -h
    - LANG=C.UTF-8 estimate_observation_richness.py -h
    - LANG=C.UTF-8 exclude_seqs_by_blast.py -h
    - LANG=C.UTF-8 extract_barcodes.py -h
    - LANG=C.UTF-8 extract_reads_from_interleaved_file.py -h
    - LANG=C.UTF-8 extract_seqs_by_sample_id.py -h
    - LANG=C.UTF-8 filter_alignment.py -h
    - LANG=C.UTF-8 filter_distance_matrix.py -h
    - LANG=C.UTF-8 filter_fasta.py -h
    - LANG=C.UTF-8 filter_otus_by_sample.py -h
    - LANG=C.UTF-8 filter_otus_from_otu_table.py -h
    - LANG=C.UTF-8 filter_samples_from_otu_table.py -h
    - LANG=C.UTF-8 filter_taxa_from_otu_table.py -h
    - LANG=C.UTF-8 filter_tree.py -h
    - LANG=C.UTF-8 fix_arb_fasta.py -h
    - LANG=C.UTF-8 group_significance.py -h
    - LANG=C.UTF-8 identify_chimeric_seqs.py -h
    - LANG=C.UTF-8 identify_missing_files.py -h
    - LANG=C.UTF-8 identify_paired_differences.py -h
    - LANG=C.UTF-8 inflate_denoiser_output.py -h
    - LANG=C.UTF-8 jackknifed_beta_diversity.py -h
    - LANG=C.UTF-8 join_paired_ends.py -h
    - LANG=C.UTF-8 load_remote_mapping_file.py -h
    - LANG=C.UTF-8 make_2d_plots.py -h
    - LANG=C.UTF-8 make_bipartite_network.py -h
    - LANG=C.UTF-8 make_bootstrapped_tree.py -h
    - LANG=C.UTF-8 make_distance_boxplots.py -h
    - LANG=C.UTF-8 make_distance_comparison_plots.py -h
    - LANG=C.UTF-8 make_fastq.py -h
    - LANG=C.UTF-8 make_library_id_lists.py -h
    - LANG=C.UTF-8 make_otu_heatmap.py -h
    - LANG=C.UTF-8 make_otu_heatmap_html.py -h
    - LANG=C.UTF-8 make_otu_network.py -h
    - LANG=C.UTF-8 make_otu_table.py -h
    - LANG=C.UTF-8 make_per_library_sff.py -h
    - LANG=C.UTF-8 make_phylogeny.py -h
    - LANG=C.UTF-8 make_prefs_file.py -h
    - LANG=C.UTF-8 make_qiime_py_file.py -h
    - LANG=C.UTF-8 make_rarefaction_plots.py -h
    - LANG=C.UTF-8 make_tep.py -h
    - LANG=C.UTF-8 map_reads_to_reference.py -h
    - LANG=C.UTF-8 merge_mapping_files.py -h
    - LANG=C.UTF-8 merge_otu_maps.py -h
    - LANG=C.UTF-8 merge_otu_tables.py -h
    - LANG=C.UTF-8 multiple_extract_barcodes.py -h
    - LANG=C.UTF-8 multiple_join_paired_ends.py -h
    - LANG=C.UTF-8 multiple_rarefactions.py -h
    - LANG=C.UTF-8 multiple_rarefactions_even_depth.py -h
    - LANG=C.UTF-8 multiple_split_libraries_fastq.py -h
    - LANG=C.UTF-8 neighbor_joining.py -h
    - LANG=C.UTF-8 nmds.py -h
    - LANG=C.UTF-8 normalize_table.py -h
    - LANG=C.UTF-8 observation_metadata_correlation.py -h
    - LANG=C.UTF-8 otu_category_significance.py -h
    - LANG=C.UTF-8 parallel_align_seqs_pynast.py -h
    - LANG=C.UTF-8 parallel_alpha_diversity.py -h
    - LANG=C.UTF-8 parallel_assign_taxonomy_blast.py -h
    - LANG=C.UTF-8 parallel_assign_taxonomy_rdp.py -h
    - LANG=C.UTF-8 parallel_assign_taxonomy_uclust.py -h
    - LANG=C.UTF-8 parallel_beta_diversity.py -h
    - LANG=C.UTF-8 parallel_blast.py -h
    - LANG=C.UTF-8 parallel_identify_chimeric_seqs.py -h
    - LANG=C.UTF-8 parallel_map_reads_to_reference.py -h
    - LANG=C.UTF-8 parallel_merge_otu_tables.py -h
    - LANG=C.UTF-8 parallel_multiple_rarefactions.py -h
    - LANG=C.UTF-8 parallel_pick_otus_blast.py -h
    - LANG=C.UTF-8 parallel_pick_otus_sortmerna.py -h
    - LANG=C.UTF-8 parallel_pick_otus_trie.py -h
    - LANG=C.UTF-8 parallel_pick_otus_uclust_ref.py -h
    - LANG=C.UTF-8 parallel_pick_otus_usearch61_ref.py -h
    - LANG=C.UTF-8 pick_closed_reference_otus.py -h
    - LANG=C.UTF-8 pick_de_novo_otus.py -h
    - LANG=C.UTF-8 pick_open_reference_otus.py -h
    - LANG=C.UTF-8 pick_otus.py -h
    - LANG=C.UTF-8 pick_rep_set.py -h
    - LANG=C.UTF-8 plot_rank_abundance_graph.py -h
    - LANG=C.UTF-8 plot_semivariogram.py -h
    - LANG=C.UTF-8 plot_taxa_summary.py -h
    - LANG=C.UTF-8 poller.py -h
    - LANG=C.UTF-8 principal_coordinates.py -h
    - LANG=C.UTF-8 print_metadata_stats.py -h
    - LANG=C.UTF-8 print_qiime_config.py -h
    - LANG=C.UTF-8 process_iseq.py -h
    - LANG=C.UTF-8 process_qseq.py -h
    - LANG=C.UTF-8 process_sff.py -h
    - LANG=C.UTF-8 quality_scores_plot.py -h
    - LANG=C.UTF-8 relatedness.py -h
    - LANG=C.UTF-8 shared_phylotypes.py -h
    - LANG=C.UTF-8 simsam.py -h
    - LANG=C.UTF-8 single_rarefaction.py -h
    - LANG=C.UTF-8 sort_otu_table.py -h
    - LANG=C.UTF-8 split_libraries.py -h
    - LANG=C.UTF-8 split_libraries_fastq.py -h
    - LANG=C.UTF-8 split_libraries_lea_seq.py -h
    - LANG=C.UTF-8 split_otu_table.py -h
    - LANG=C.UTF-8 split_otu_table_by_taxonomy.py -h
    - LANG=C.UTF-8 split_sequence_file_on_sample_ids.py -h
    - LANG=C.UTF-8 start_parallel_jobs.py -h
    - LANG=C.UTF-8 start_parallel_jobs_sc.py -h
    - LANG=C.UTF-8 start_parallel_jobs_slurm.py -h
    - LANG=C.UTF-8 start_parallel_jobs_torque.py -h
    - LANG=C.UTF-8 subsample_fasta.py -h
    - LANG=C.UTF-8 summarize_otu_by_cat.py -h
    - LANG=C.UTF-8 summarize_taxa.py -h
    - LANG=C.UTF-8 summarize_taxa_through_plots.py -h
    - LANG=C.UTF-8 supervised_learning.py -h
    - LANG=C.UTF-8 swarm_breaker.py -h
    - LANG=C.UTF-8 transform_coordinate_matrices.py -h
    - LANG=C.UTF-8 tree_compare.py -h
    - LANG=C.UTF-8 trflp_file_to_otu_table.py -h
    - LANG=C.UTF-8 trim_sff_primers.py -h
    - LANG=C.UTF-8 truncate_fasta_qual_files.py -h
    - LANG=C.UTF-8 truncate_reverse_primer.py -h
    - LANG=C.UTF-8 unweight_fasta.py -h
    - LANG=C.UTF-8 upgma_cluster.py -h
    - LANG=C.UTF-8 validate_demultiplexed_fasta.py -h
    - LANG=C.UTF-8 validate_mapping_file.py -h

about:
  home: http://www.qiime.org
  license: GNU General Public License v2 (GPLv2)
  summary: 'Quantitative Insights Into Microbial Ecology'
