package:
  name: crimson
  version: 0.3.0

source:
  fn: Crimson-0.3.0.tar.gz
  url: https://pypi.python.org/packages/bf/8e/cdddc397f92fc1199195f01446bd3407dcb6f6ab8983f32a5e8798348809/Crimson-0.3.0.tar.gz
  md5: 2087a80794c3d579058bbe4a93a6d39a

build:
  number: 0
  entry_points:
    - crimson=crimson.main:cli

requirements:
  build:
    - python
    - setuptools
    - click >=6.6
    - pyyaml >=3.11
    - wheel >=0.23.0

  run:
    - python
    - click >=6.6
    - pyyaml >=3.11

test:
  imports:
    - crimson

  commands:
    # click requires a unicode locale
    - LANG=C.UTF-8 crimson --help

about:
  home: https://github.com/bow/crimson
  license: BSD License
  summary: 'Bioinformatics tool outputs converter to JSON or YAML.'
  license_family: BSD

extra:
  container:
    # click relies on unicode support, which is not present in the default busybox image
    base: bioconda/extended-base-image
